### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by Jerry-Z07** [zouXH-god/nonebot-plugin-ACGalaxy#2]
Ubuntu 22.04
nb 2.3
无论发送什么命令，均出现如下错误

```
AlconnaMatcher(type='', module=nonebot-plugin-ACGalaxy.acg, lineno=11) failed.
Traceback (most recent call last):
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 154, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 68, in start_tls
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot-plugin-ACGalaxy/acg.py", line 23, in acg_calendar_g
    acg_list = await get_acg_list(city_name=city, count=100, order="time")
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/nonebot-plugin-ACGalaxy/utils.py", line 33, in get_acg_list
    response = await client.get(url, params=params)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/lxmb/桌面/bots/nb-game/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

```
从报错上看似乎是网络问题，但我尝试了多种网况（三网 🪜）均无法连接到`https://acg.s1f.ren`

**Comment by zouXH-god** [comment]
那会更新了一下，有一段时间用不了，现在正常了

**Comment by Jerry-Z07** [comment]
有点迷惑，今天用的时候又这样报错
*不会我使用的时候又卡在更新维护的时间点吧*

**Comment by zouXH-god** [comment]
还真被你撞上了，前几天ip换了我忘记换解析了，现在正常了 ~(๑•́ ₃ •̀๑)

**Comment by Jerry-Z07** [comment]
~~那我运气还真挺好的~~
实测已恢复正常
